name: build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run : pip install mkdocs >=1.1.2
      - run : pip install mkdocs-git-committers-plugin-2>=1.1.1
      - run : pip install mkdocs-git-revision-date-localized-plugin>=1.0
      - run : pip install mkdocs-minify-plugin>=0.3
      - run : pip install mkdocs-rss-plugin>=1.2
      - run : pip install mkdocs-redirects>=1.0
      - run : pip install pillow
      - run: pip install --force-reinstall mkdocs-material>=5.0.0b2
      - run: pip install pymdown-extensions
      - run: pip install pygments
      - run: pip install mkdocs-htmlproofer-plugin
      - run: mkdocs gh-deploy --force --clean --verbose
      - name: Install poetry
        run: |
          python3 -m pip install --upgrade poetry==1.4.0
      - name: Setup Python (poetry)
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry install
      - run: poetry run mkdocs build
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: ./site
